apiVersion: batch/v1
kind: Job
metadata:
  name: inference-job
spec:
  template:
    spec:
      securityContext:
            runAsGroup: 3000
            runAsUser: 3000
      containers:
      - name: inference-container
        imagePullPolicy: Never
        image: k8-model:latest
        command: ["python3",  "inference.py"]
      restartPolicy: Never
  backoffLimit: 0